baseURL = 'https://jiaaomario.github.io/blog/'
languageCode = "en-us"
theme = "hyde"
title = '加奥的个人博客'

[params]
  description = "加奥的个人博客"
  sidebarPosition = "left"

[menu]

  [[menu.main]]
    name = "文章"
    url = "/post/"
    weight = 2
